#!/bin/bash

# Script that runs the PigScript cullNgrams.pig with
# command line paramters. Result is echoed to the console.

USAGE="Usage: cullNgrams   [{-h | --help}] \n
                           \t\t\t [{-x | --execmode] {local | mapreduce}] \n
                           \t\t\t [{-s | --stopwords}] (default: no stopword removal)\n
                           \t\t\t [{-i | --minlength}] (default: 2)\n
                           \t\t\t [{-a | --maxlength}] (default: 25)\n
                           \t\t\t <ngramFilePathOrDirOnHDFS> \n
    \tExample: cullNgrams Dataset/dmozNgrams.csv.gz \n
    \tExample: cullNgrams Dataset/myNgramDir \n
    \tExample: cullNgrams -d /user/doe/mycounts Dataset/googleNgrams.csv.gz \n"

# Defaults:
EXEC_MODE=mapreduce
FILTER_STOPWORDS=0
WORD_LEN_MIN=2
WORD_LEN_MAX=25

SHORTOPTS="hx:si:a:"
LONGOPTS="help,execmode:stopwords,minlength:,maxlength:"

ARGS=`getopt -s bash --options=$SHORTOPTS  \
  --longoptions=$LONGOPTS --name=$PROGNAME -- "$@"`

eval set -- "$ARGS"

while true; do
   case $1 in
      -h|--help)
         echo -e $USAGE
         exit 0
         ;;
      -x|--execmode)
         shift
         EXEC_MODE=$1
         ;;
      -s|--stopwords)
	 FILTER__STOPWORDS=1
	 ;;
      -i|--minlength)
	 shift
	 WORD_LEN_MIN=$1
	 ;;
      -a|--maxlength)
	 shift
	 WORD_LEN_MAX=$1
	 ;;
      --)
         shift
         break
         ;;
      *)
         shift
         break
         ;;
   esac
   # Throw away the '--' that's added by getopt.
   # The -- case above doesn't get hit when user
   # forgets to put in any required args.
   shift
done

if [ -z $DEST_DIR ]
then    
    if [ $EXEC_MODE == local ] 
    	then
    	    DEST_DIR=`pwd`
    	else
    	    DEST_DIR='/user/'`whoami`
    fi     
fi    

if [ $# == 0 ] 
then
    echo "Missing path to ngram file or directory."
    echo -e $USAGE
    exit -1
else
    NGRAM_NAME=$1
fi

# If we are running in cygwin, we have to convert the 
# path to the Pig script into a Windows path:

export SCRIPT_DIR=`dirname $0`
if [[ `uname` == *CYGWIN* ]]
then 
  export SCRIPT_DIR=`cygpath --mixed ${SCRIPT_DIR}`
fi

# Check whether the ngram target file exists.
# If so, Pig would run for a long time, and then die. Make
# this more fail-fast:

EXISTENCE=`hadoop fs -stat ${DEST_DIR}/${NGRAM_NAME}_culled.gz 2> /dev/null` 
if [ -n "$EXISTENCE" ]
then
    echo "File ${DEST_DIR}/${NGRAM_NAME}_culled.gz already exists. Quitting."
    exit -1
fi

echo "Starting cullNgrams:
Exec mode: -x $EXEC_MODE
Input file : $NGRAM_NAME
Output file: ${DEST_DIR}/${NGRAM_NAME}_culled.gz"

 pigrun -x $EXEC_MODE \
         FILTER_STOPWORDS=${FILTER_STOPWORDS} \
         WORD_LEN_MIN=${WORD_LEN_MIN} \
         WORD_LEN_MAX=${WORD_LEN_MAX} \
         CULLED_DEST=${DEST_DIR}/${NGRAM_NAME}_culled.gz \
         NGRAM_FILE=$NGRAM_NAME \
         ${SCRIPT_DIR}/Pig/cullNgrams.pig

exit 0
