#!/bin/bash

# Script that runs the PigScript ngramFrequencies.pig with
# command line paramters. Result is echoed to the console.

USAGE="Usage: ngramFrequencies   [{-h | --help}] \n
                           \t\t\t [{-x | --execmode] {local | mapreduce}] \n
                           \t\t\t <ngramFilePathOrDirOnHDFS> \n
    \tOutput to <inputFile_freqs> \n
    \tExample: ngramFrequencies Dataset/dmozNgrams.csv.gz \n
    \tExample: ngramFrequencies Dataset/myNgramDir \n
    \tExample: ngramFrequencies -d /user/doe/mycounts Dataset/googleNgrams.csv.gz \n"

EXEC_MODE=mapreduce

SHORTOPTS="hx:"
LONGOPTS="help,execmode:"

ARGS=`getopt -s bash --options=$SHORTOPTS  \
  --longoptions=$LONGOPTS --name=$PROGNAME -- "$@"`

eval set -- "$ARGS"

while true; do
   case $1 in
      -h|--help)
         echo -e $USAGE
         exit 0
         ;;
      -x|--execmode)
         shift
         EXEC_MODE=$1
         ;;
      -d|--destdir)
         shift
         DEST_DIR=$1
         ;;
      --)
         shift
         break
         ;;
      *)
         shift
         break
         ;;
   esac
   # Throw away the '--' that's added by getopt.
   # The -- case above doesn't get hit when user
   # forgets to put in any required args.
   shift
done

if [ -z $DEST_DIR ]
then    
    if [ $EXEC_MODE == local ] 
    	then
    	    DEST_DIR=`pwd`
    	else
    	    DEST_DIR='/user/'`whoami`
    fi     
fi    

if [ $# == 0 ] 
then
    echo "Missing path to ngram file or directory."
    echo -e $USAGE
    exit -1
else
    NGRAM_NAME=$1
fi

# If we are running in cygwin, we have to convert the 
# path to the Pig script into a Windows path:

export SCRIPT_DIR=`dirname $0`
if [[ `uname` == *CYGWIN* ]]
then 
  export SCRIPT_DIR=`cygpath --mixed ${SCRIPT_DIR}`
fi

# Check whether the ngram target file exists.
# If so, Pig would run for a long time, and then die. Make
# this more fail-fast:

EXISTENCE=`hadoop fs -stat ${DEST_DIR}/${NGRAM_NAME}_freqs.gz 2> /dev/null` 
if [ -n "$EXISTENCE" ]
then
    echo "File ${DEST_DIR}/${NGRAM_NAME}_freqs.gz already exists. Quitting."
    exit -1
fi

echo "Starting cullNgrams:
Exec mode: -x $EXEC_MODE
Input file : $NGRAM_NAME
Output file: ${DEST_DIR}/${NGRAM_NAME}_freqs.gz"

 pigrun -x $EXEC_MODE \
         FREQS_DEST=${DEST_DIR}/${NGRAM_NAME}_freqs.gz \
         NGRAM_FILE=$NGRAM_NAME \
         ${SCRIPT_DIR}/ngramFrequencies.pig


echo "NOTE: If you use GoodTuring as implemented in http://www.grsampson.net/D_SGT.c, not having first entry be "1 x", where x may not be 0 will not move probaility mass to unseen ngrams. Probably makes little difference for large ngram files."

exit 0
