#!/bin/bash

usage="Usage: warcWordCount WARCDataSetFilePathOnHDFS [destFileOnHDFS] (Default output is stdout.)"

if [ $# -lt 1 ] || [ $# -gt 2 ]
then 
  echo ${usage}
  exit
else
  srcFile=$1
fi

if [ $# -gt 1 ] 
then
  OUTPUT_COMMAND="STORE wordCounts INTO '$2' USING org.apache.pig.piggybank.storage.CSVExcelStorage()"
else
  OUTPUT_COMMAND="DUMP wordCounts";
fi

#**************
#pigrun srcFile=$srcFile $HOME/PigIR/PigScripts/CommandLineUtils/warcWordCount.pig
echo "OUTPUT_COMMAND is '$OUTPUT_COMMAND'."
pigrun -x local srcFile=$srcFile $HOME/PigIR/PigScripts/CommandLineUtils/warcWordCount.pig
#**************
